# Generated by Django 4.1.13 on 2024-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('order_item_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('shipment_status', models.CharField(max_length=50)),
                ('shipment_type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
