# Generated by Django 4.1.13 on 2024-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0002_alter_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
